# Generated by Django 5.0.4 on 2024-04-17 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(55)])),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Introduce yourself', max_length=500, null=True)),
                ('address', models.CharField(default='Քանաքեռ', max_length=30, verbose_name='by default is Քանաքեռ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March')], max_length=10)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Անձ',
                'verbose_name_plural': 'Մարդիկ',
            },
        ),
    ]
