# Generated by Django 5.0.4 on 2024-04-20 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('year', models.DateField()),
                ('book_category', models.CharField(choices=[('detective', 'detective'), ('adventure', 'adventure'), ('science', 'science'), ('melodrama', 'melodrama'), ('drama', 'drama')], max_length=10)),
                ('description', models.TextField(blank=True, help_text='About book', max_length=500, null=True)),
                ('pages', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)])),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.CharField(default='Edit-Print', max_length=30, verbose_name='by default is Edit-Print')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Գիրք',
                'verbose_name_plural': 'Գրքեր',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('BMW', 'BMW'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Range-Rover', 'Range-Rover'), ('Opel', 'Opel'), ('Toyota', 'Toyota'), ('Honda', 'Honda'), ('Nissan', 'Nissan')], max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('VIN_code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Enter a brief description of your car', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Մեքենա',
                'verbose_name_plural': 'Մեքենաներ',
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_after', models.CharField(max_length=30, unique=True)),
                ('school_number', models.PositiveSmallIntegerField(max_length=30, unique=True)),
                ('address', models.CharField(default='Armenia/Yerevan', max_length=30, verbose_name='by default is Yerevan')),
                ('director', models.CharField(max_length=30)),
                ('classes_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(48)])),
                ('classrooms_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(48)])),
                ('teachers_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(48)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Դպրոց',
                'verbose_name_plural': 'Դպրոցներ',
            },
        ),
        migrations.CreateModel(
            name='TheClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('stream', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=2)),
                ('description', models.TextField(blank=True, help_text='A little about class', max_length=50, null=True)),
                ('students_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(30)])),
                ('lessons_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)])),
                ('teacher', models.CharField(choices=[('Safaryan', 'Safaryan'), ('Kirakosyan', 'Kirakosyan'), ('Harutyunyan', 'Harutyunyan'), ('Chevlikyan', 'Chevlikyan'), ('Nersesyan', 'Nersesyan'), ('Karoyan', 'Karoyan'), ('Matshkalyan', 'Matshkalyan')], max_length=30)),
                ('wanted_language', models.CharField(default='English', max_length=30, verbose_name='by default is English')),
            ],
            options={
                'verbose_name': 'դասարան',
                'verbose_name_plural': 'դասարաններ',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
