# Generated by Django 5.0.4 on 2024-04-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0002_book_car_school_theclass_alter_person_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
