# Generated by Django 5.0.4 on 2024-04-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0003_alter_school_school_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='Edit-Print', max_length=30, verbose_name='printed inby default is Edit-Print'),
        ),
    ]
