# Generated by Django 5.0.4 on 2024-04-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapplication', '0007_alter_theclass_wanted_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(default='Yerevan', max_length=30, verbose_name='address (by default is Yerevan)'),
        ),
    ]
